name: AdvancedReplay
version: ${project.version}
main: me.jumper251.replay.ReplaySystem
authors: [Jumper251,Delta203]
depend: [ProtocolLib]
commands:
  replay:
    permissions: replay.command
    description: Main Replay command
    aliases: [rp]